---
title: "Functions Example"
author: "David Keyes"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(tidyverse)
library(flextable)
library(janitor)
library(scales)
```

```{r}
schools <- read_csv("EducationDataPortal_10.04.2019_schools.csv")
```

# Introduction 

This is a report about the top 15 largest schools in California, Oregon, Washington, Montana, and Idaho.

# California

```{r}
top_schools <- function(state_to_filter) {
  schools %>% 
    filter(state_name == state_to_filter) %>% 
    top_n(15, enrollment) %>% 
    arrange(desc(enrollment)) %>% 
    mutate(enrollment = comma(enrollment)) %>% 
    select(-state_name) %>% 
    set_names(c("School", "Enrollment")) %>% 
    flextable() %>% 
    align(align = "left", j = 1, part = "all") %>% 
    width(width = 2.5)
}


top_schools("California")



```

# Oregon

```{r}
top_schools("Oregon")
```

# Washington

```{r}
top_schools("Washington")
```

# Montana

```{r}
top_schools("Montana")
```

# Idaho

```{r}
top_schools("Idaho")
```