

```{r}
library(tidyverse)
questions <- tribble(
  ~question, ~yes_rate,
  'Should we have more chocolate?', 0.83,
  'Do penguins have knees?', 0.25,
  'Would you enjoy being a dog?', 0.6
)
```

```{r}
questions |> 
  mutate(question = fct_reorder(question, yes_rate)) |> 
  ggplot(aes(y = question, x = yes_rate)) +
  geom_col(fill = '#3087CF') +
  labs(
    x = element_blank(), 
    y = element_blank(),
    title = 'How many people say "Yes" to these questions?'
  ) +
  theme_minimal(base_size = 20, base_family = 'Source Sans Pro') +
  theme(
    plot.title.position = 'plot',
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank()
  )  +
  scale_x_continuous(labels = scales::label_percent())
```


```{r}
complementary_rates <- questions |> 
  mutate(
    no_rate = 1 - yes_rate,
    question = fct_reorder(question, yes_rate)
  ) |> 
  pivot_longer(
    cols = -question,
    names_to = 'answer',
    names_pattern = '(.+)_rate',
    values_to = 'percentage'
  )
```

```{r}
complementary_rates |> 
  ggplot(aes(y = question, x = percentage, fill = answer)) +
  geom_col() + 
  geom_vline(xintercept = 0.5, color = 'grey20', linetype = 2) +
  labs(
    x = element_blank(), 
    y = element_blank(),
    title = 'How many people say "Yes" to these questions?'
  ) +
  theme_minimal(base_size = 20, base_family = 'Source Sans Pro') +
  theme(
    plot.title.position = 'plot',
    panel.grid.minor = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position = 'none'
  )  +
  scale_x_continuous(labels = scales::label_percent()) +
  scale_fill_manual(
    values = c('yes' = '#3087CF'),
    na.value = 'grey80'
  )
```
























