

```{r}
library(tidyverse)
set.seed(345345)
palmerpenguins::penguins |> 
  ggplot(aes(x = bill_length_mm, y = species, fill = species)) +
  geom_jitter(shape = 21, size = 4, alpha = 0.75) +
  labs(
    title = 'Adelie Penguins Have Shorter Bills',
    x = 'Bill length (in mm)',
    y = element_blank(), 
    fill = 'Species',
    caption = 'Data: {palmerpenguins} R package'
  ) +
  theme_minimal(base_size = 18, base_family = 'Source Sans Pro') +
  theme(
    text = element_text(
      colour = 'grey30'
    ),
    plot.title.position = 'plot',
    plot.caption.position = 'plot'
  ) +
  scale_fill_manual(
    values = c("#E69F00", "#009E73", "#0072B2")
  )
```



```{r}
palmerpenguins::penguins |> 
  ggplot(aes(x = bill_length_mm, y = species, fill = species)) +
  geom_jitter(shape = 21, size = 4, alpha = 0.75) +
  labs(
    title = 'Adelie Penguins Have Shorter Bills',
    x = 'Bill length (in mm)',
    y = element_blank(), 
    fill = 'Species',
    caption = 'Data: {palmerpenguins} R package'
  ) +
  ggthemes::theme_fivethirtyeight(base_size = 18) +
  theme(
    text = element_text(
      colour = 'grey30'
    ),
    plot.title.position = 'plot',
    plot.caption.position = 'plot'
  )  +
  scale_fill_manual(
    values = c("#E69F00", "#009E73", "#0072B2")
  )
```




