

```{r}
library(tidyverse)
flights <- nycflights13::flights
flights_subset <- flights |>
  select(year:sched_dep_time) |>
  slice(1:3, .by = month) |>
  arrange(month)
```

```{r}
flights_subset |>
  mutate(
    date = make_date(year = year, month = month, day = day),
    day_of_year = yday(date),
    day_of_month = mday(date),
    day_of_week = wday(date),
    week_of_year = week(date)
  ) |>
  select(date:week_of_year)
```

```{r}
counts <- flights |>
  mutate(
    date = make_date(year = year, month = month, day = day),
    day_of_week = wday(date),
    week_of_year = week(date)
  ) |>
  count(day_of_week, week_of_year)

counts |>
  ggplot(aes(x = week_of_year, y = day_of_week, fill = n)) +
  geom_tile(col = "white") +
  theme_minimal(base_size = 16, base_family = "Source Sans Pro") +
  coord_equal() +
  scale_fill_gradient(high = "#404E6B", low = "white") +
  labs(
    y = element_blank(),
    x = "Week",
    fill = "Flights",
    title = "Number of flights in NYC in 2013"
  )
```


```{r}
flights_subset |>
  mutate(
    date = make_date(year = year, month = month, day = day),
    day_of_week = wday(date),
    day_of_week_label = wday(
      date,
      label = TRUE,
      locale =  "en_US.UTF-8"
    ),
    day_of_week_full_label = wday(
      date,
      label = TRUE,
      abbr = FALSE,
      locale =  "en_US.UTF-8"
    ),
  ) |>
  select(date, day_of_week, day_of_week_label, day_of_week_full_label)
```

```{r}
converted_times <- flights_subset |>
  mutate(
    dep_time = make_datetime(
      year, month, day,
      hour = dep_time %/% 100, # integer division
      min = dep_time %% 100 # get remainder
    ),
    sched_dep_time = make_datetime(
      year, month, day,
      hour = sched_dep_time %/% 100,
      min = sched_dep_time %% 100
    ),
    departure_delay = dep_time - sched_dep_time
  )
```


```{r}
converted_times |>
  mutate(
    departure_interval = interval(
      start = sched_dep_time, 
      end = dep_time
    ),
    delay_in_mins = departure_interval / minutes(1),
    delay_in_hrs = departure_interval / hours(1),
    delay_in_10min_blocks = departure_interval / minutes(10),
    delay_in_1.5min_blocks = departure_interval / (
      minutes(1) + seconds(30)
    )
  ) |>
  select(delay_in_mins:delay_in_1.5min_blocks) |>
  slice(4)
```














