---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(palmerpenguins)
library(ggh4x)

penguins_summary <-
  penguins |>
  group_by(year, sex) |>
  summarize(mean_weight = mean(body_mass_g, na.rm = TRUE)) |>
  ungroup() |>
  drop_na() |>
  ggplot(aes(
    year,
    mean_weight,
    group = sex,
    color = sex
  )) +
  geom_line(
    linewidth = 1
  ) +
  coord_axes_inside(
    xintercept = 2007.21,
    labels_inside = TRUE
  ) +
  scale_x_continuous(
    breaks = c(2007, 2008, 2009),
    expand = expansion(0, 0.05)
  ) +
  scale_y_continuous(
    limits = c(0, 5000),
    breaks = seq(0, 5000, 1000),
    labels = c(
      "0",
      "1,000",
      "2,000",
      "3,000",
      "4,000",
      "5,000 grams"
    )
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.title = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(
      linetype = "dotted",
      color = "grey70"
    ),
    axis.text.x = element_text(
      vjust = -2
    ),
    axis.text.y = element_text(
      vjust = -1,
      hjust = 0
    ),
    axis.ticks.x = element_line(color = "grey30"),
    axis.ticks.length.x = unit(0.5, "line"),
    axis.line.x = element_line(color = "grey30"),
    legend.position = "none"
  )
```

```{r}
ggplot(mpg, aes(displ - mean(displ), hwy - mean(hwy))) +
  geom_point() +
  theme(axis.line = element_line()) +
  coord_axes_inside()
```
